Add Email bean validation annotation for "format":"email"
joelittlejohn/jsonschema2pojo pull request #1475
Opened 2023-02-04 17:56 UTC by joelittlejohn

2023-02-04 17:58 UTC, joelittlejohn commented
If you receive compilation errors because javax.validation.constraints.Email cannot be found, upgrade to javax.validation/validation-api 2.0.1.Final.

2023-02-04 18:24 UTC, unkish requested changes

2023-02-04 18:24 UTC, unkish commented on jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/PropertyRule.java
> +        } else if ("email".equalsIgnoreCase(format) && ruleFactory.getGenerationConfig().isIncludeJsr303Annotations()) {
Would be nice to have some tests as well

2023-02-05 07:51 UTC, unkish reviewed
Added few comments

2023-02-05 07:51 UTC, unkish commented on jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/PropertyRule.java
> +import jakarta.validation.constraints.Email;
Nitpick: currently this is unused import, since fully-qualified class name is used on L207.

2023-02-05 07:51 UTC, unkish commented on jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/config/IncludeJsr303AnnotationsIT.java
> +    public void jsr303EmailValidationIsAddedForFormatEmailSchemaRule() throws ClassNotFoundException {
A non-related "issue": would it make sense to fix typo by renaming `jar303AnnotationsValidatedForAdditionalProperties` to `jsr303AnnotationsValidatedForAdditionalProperties` ?

2023-02-05 07:59 UTC, unkish commented
> **If you receive compilation errors because javax.validation.constraints.Email cannot be found, upgrade to javax.validation/validation-api 2.0.1.Final.**

Note that given annotation can't be used when `targetVersion` is less that `1.8` as it has:

- `@Retention(RUNTIME)`
- `@Target` contains `TYPE_USE` which is available since `1.8`

Those who target older version might need to make sure that version of `javax.validation/validation-api` being used is compatible with `targetVersion`

2023-02-05 13:33 UTC, merged

2023-02-05 16:31 UTC, unkish commented
Nice work!